RentalBooks/RentalBooks/Controllers/BookController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RentalBooks.Models;
using RentalBooks.Abstract;

namespace RentalBooks.Controllers
{
    public class BookController : Controller
    {
        //private IEnumerable<Book> ListOfBooks=null;
        private IBookRepository repo;
        public int PageSize = 2;
        //
        // GET: /Book/
        private List<Book> books;
        public BookController(IBookRepository repo)
        {
            this.repo = repo; books = repo.Books.ToList();
        }
        public ViewResult Index()
        {
            return View(repo.Books);
        }
            
        public ViewResult Edit(int bookId, string rUrl)
        {
            Book bk = repo.Books.FirstOrDefault(b => b.BookID == bookId);
            return View(new ItemViewModel { book = bk, returnUrl = rUrl });
        }

        [HttpPost]
        public ActionResult Edit(Book book) //Edit(Book book, string returnUrl)
        {
            if (ModelState.IsValid)
            {
                repo.SaveBook(book);
                return RedirectToAction("Index");
            }
            else
            {
                // problems
                return View(book);
            }
        }
        public RedirectToRouteResult Edition(int bookId, string returnUrl)
        {
            return RedirectToAction("Edit", new { bookId, rUrl=returnUrl } );
        }


        public ViewResult List(int page = 1)
        {
            //if (ListOfBooks == null) { ListOfBooks = new LibraryContext().Books.ToList(); }
            ViewBag.Title = "Lend a Book ...";
            BooksListViewModel viewModel = new BooksListViewModel
            {
                books = books.OrderBy(b => b.BookID).Skip((page - 1) * PageSize).Take(PageSize),
                pagingInfo = new PagingInfo { CurrentPage = page, ItemsPerPage = PageSize, TotalItems = repo.Books.Count() }
            };
            return View(viewModel);
        }


        //
        // GET: /Book/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        //
        // GET: /Book/Create
        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Book/Create
        //[HttpPost]
        //public ActionResult Create(FormCollection collection)
        //{
        //    try
        //    {
        //        // TODO: Add insert logic here

        //        return RedirectToAction("Index");
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}

        //
        // GET: /Book/Edit/5
        //public ActionResult Edit(int id)
        //{
        //    return View();
        //}

        //
        // POST: /Book/Edit/5
        //[HttpPost]
        //public ActionResult Edit(int id, FormCollection collection)
        //{
        //    try
        //    {
        //        // TODO: Add update logic here

        //        return RedirectToAction("Index");
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}

        //
        // GET: /Book/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        //
        // POST: /Book/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

RentalBooks/RentalBooks/Views/Shared/BookSummary.cshtml
@using RentalBooks.Models
@model RentalBooks.Models.Book
<div class="row">
    <table class="table table-striped table-hover ">
        <thead><tr><th>Book</th><th><b>@Model.Title</b></th><th>What Is That Book About ?</th></tr></thead>
        <tr class="info">
            <th>Authors:</th>
            <td>
                @foreach (Author a in @Model.Authors)
                {
                    @a.Name @:&#32
                    @a.Surname
                    @:(
                    @a.Nick @:)
                    <br />
                }
            </td>
            @if (Model.Quantity > 0)
            {
                <td rowspan="5">@Model.ShortDescription</td> }
            else
            {
                <td rowspan="4">@Model.ShortDescription</td> }
        </tr>
        <tr>
            <th>Categories:</th>
            <td>
                @foreach (Category c in @Model.Categories)
                {
                    @c.CatDescription; @:<br />
             }
            </td>
        </tr>
        <tr><th>Publisher:</th><td>@Model.Publisher</td></tr>
        <tr><th>Availability:</th><td>@Model.Quantity.ToString() </td></tr>
        @if (Model.Quantity > 0)
        {
            <tr>
                <th>Order:</th>
                <td>
                    @using (Html.BeginForm("AddToCart", "Cart"))
                    {
                        @Html.Hidden("bookId", @Model.BookID);
                        @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
                        <input type="submit" value="Take to Cart!" class="btn btn-info" />
                    }
                </td>
            </tr>
        }
         <tr>
        <th>Link to Cover:</th>
        <td>
            @if (Request.IsAuthenticated && User.IsInRole("Admin"))
            {
                        using (Html.BeginForm("Edition", "Book"))
        {
            @Html.Hidden("bookId", @Model.BookID);
            @Html.Hidden("returnUrl", Request.Url.PathAndQuery);
            @:<input type="submit" value="Edit" class="btn btn-danger"  />
        }
 
            }
         </td>

        <td>
            @if (Model.Cover != null)
            {
             <a href="@Model.Cover">Take a look here!</a>
            }
        </td>
        </tr>
        <tr><th colspan="3">The Best Pieces ...</th></tr>
        <tr><td colspan="3">@Model.Textpart</td></tr>
    </table>



    </div>

RentalBooks/RentalBooks/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - ADMINISTRATION BACKSTAGE</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="container body-content">
            <ul class="breadcrumb">
                <li class="active">@Html.ActionLink("Home", "Index", "Home")</li>
            </ul>
        <div class="panel panel-warning">
            <div class="panel-heading">
                <h3 class="panel-title">Administration Backstage</h3>
            </div>

            @if (TempData["message"] != null)
            {
                <div class="Message">@TempData["message"]</div>
            }
            @RenderBody()
        </div>
</div>
        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)
</body>
</html>

RentalBooks/RentalBooks/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - "Пусти Бригу Узми Книгу"</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Review of books", "List", "Book", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>

                    @if (Request.IsAuthenticated && User.IsInRole("Admin")) {
                        <li>@Html.ActionLink("RolesAdmin", "Index", "RolesAdmin")</li>
                        <li>@Html.ActionLink("UsersAdmin", "Index", "UsersAdmin")</li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - "Пусти Бригу Узми Книгу"</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>